name = "TextGrids"
uuid = "283d22f6-ba7c-4935-ba44-d56525675179"
authors = ["Justin Lo <37448886+justinjhlo@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
StringEncodings = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
